/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminVehiclesRouteImport } from './routes/admin.vehicles'
import { Route as AdminSystemLogsRouteImport } from './routes/admin.system-logs'
import { Route as AdminServiceTypeManagerRouteImport } from './routes/admin.service-type-manager'
import { Route as AdminRbacRouteImport } from './routes/admin.rbac'
import { Route as AdminProfessionalTaxManagerRouteImport } from './routes/admin.professional-tax-manager'
import { Route as AdminPayrollManagerRouteImport } from './routes/admin.payroll-manager'
import { Route as AdminPayrollDaysManagerRouteImport } from './routes/admin.payroll-days-manager'
import { Route as AdminPayrollRouteImport } from './routes/admin.payroll'
import { Route as AdminOffboardingReasonManagerRouteImport } from './routes/admin.offboarding-reason-manager'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminLwfManagerRouteImport } from './routes/admin.lwf-manager'
import { Route as AdminLanguageManagerRouteImport } from './routes/admin.language-manager'
import { Route as AdminInventoryRouteImport } from './routes/admin.inventory'
import { Route as AdminExServiceManagerRouteImport } from './routes/admin.ex-service-manager'
import { Route as AdminEsicBranchManagerRouteImport } from './routes/admin.esic-branch-manager'
import { Route as AdminEmployeesRouteImport } from './routes/admin.employees'
import { Route as AdminDutyManagerRouteImport } from './routes/admin.duty-manager'
import { Route as AdminDesignationManagerRouteImport } from './routes/admin.designation-manager'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminCostComponentManagerRouteImport } from './routes/admin.cost-component-manager'
import { Route as AdminControlCenterRouteImport } from './routes/admin.control-center'
import { Route as AdminCompanyDocumentsRouteImport } from './routes/admin.company-documents'
import { Route as AdminBillingTypeManagerRouteImport } from './routes/admin.billing-type-manager'
import { Route as AdminAttendanceCodeManagerRouteImport } from './routes/admin.attendance-code-manager'
import { Route as AdminAttendanceRouteImport } from './routes/admin.attendance'
import { Route as AdminAssetManagerRouteImport } from './routes/admin.asset-manager'
import { Route as AdminAllowanceManagerRouteImport } from './routes/admin.allowance-manager'
import { Route as AdminPayrollIndexRouteImport } from './routes/admin.payroll.index'
import { Route as AdminAttendanceIndexRouteImport } from './routes/admin.attendance.index'
import { Route as AdminVehiclesServiceManagerRouteImport } from './routes/admin.vehicles.service-manager'
import { Route as AdminVehiclesPucsRouteImport } from './routes/admin.vehicles.pucs'
import { Route as AdminVehiclesInventoryRouteImport } from './routes/admin.vehicles.inventory'
import { Route as AdminVehiclesInsurancesRouteImport } from './routes/admin.vehicles.insurances'
import { Route as AdminVehiclesInsightLabRouteImport } from './routes/admin.vehicles.insight-lab'
import { Route as AdminVehiclesFastagsRouteImport } from './routes/admin.vehicles.fastags'
import { Route as AdminVehiclesExpenseManagerRouteImport } from './routes/admin.vehicles.expense-manager'
import { Route as AdminPayrollUnitIdRouteImport } from './routes/admin.payroll.$unitId'
import { Route as AdminInventoryWriteOffsRouteImport } from './routes/admin.inventory.write-offs'
import { Route as AdminInventoryWarehousesRouteImport } from './routes/admin.inventory.warehouses'
import { Route as AdminInventoryVendorsRouteImport } from './routes/admin.inventory.vendors'
import { Route as AdminInventoryTransfersRouteImport } from './routes/admin.inventory.transfers'
import { Route as AdminInventoryStockRouteImport } from './routes/admin.inventory.stock'
import { Route as AdminInventoryPurchaseOrdersRouteImport } from './routes/admin.inventory.purchase-orders'
import { Route as AdminInventoryItemsRouteImport } from './routes/admin.inventory.items'
import { Route as AdminInventoryIssuancesRouteImport } from './routes/admin.inventory.issuances'
import { Route as AdminInventoryGoodsReceiptsRouteImport } from './routes/admin.inventory.goods-receipts'
import { Route as AdminInventoryDashboardRouteImport } from './routes/admin.inventory.dashboard'
import { Route as AdminInventoryAdjustmentsRouteImport } from './routes/admin.inventory.adjustments'
import { Route as AdminCustomersUnitManagerRouteImport } from './routes/admin.customers.unit-manager'
import { Route as AdminCustomersStateManagerRouteImport } from './routes/admin.customers.state-manager'
import { Route as AdminCustomersCustomerManagerRouteImport } from './routes/admin.customers.customer-manager'
import { Route as AdminCustomersBranchManagerRouteImport } from './routes/admin.customers.branch-manager'
import { Route as AdminContractsClientContractsRouteImport } from './routes/admin.contracts.client-contracts'
import { Route as AdminAttendanceUnitIdRouteImport } from './routes/admin.attendance.$unitId'
import { Route as AdminCandidatesIdDetailsRouteImport } from './routes/admin.candidates.$id.details'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVehiclesRoute = AdminVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemLogsRoute = AdminSystemLogsRouteImport.update({
  id: '/system-logs',
  path: '/system-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServiceTypeManagerRoute = AdminServiceTypeManagerRouteImport.update({
  id: '/service-type-manager',
  path: '/service-type-manager',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRbacRoute = AdminRbacRouteImport.update({
  id: '/rbac',
  path: '/rbac',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfessionalTaxManagerRoute =
  AdminProfessionalTaxManagerRouteImport.update({
    id: '/professional-tax-manager',
    path: '/professional-tax-manager',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminPayrollManagerRoute = AdminPayrollManagerRouteImport.update({
  id: '/payroll-manager',
  path: '/payroll-manager',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPayrollDaysManagerRoute = AdminPayrollDaysManagerRouteImport.update({
  id: '/payroll-days-manager',
  path: '/payroll-days-manager',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPayrollRoute = AdminPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOffboardingReasonManagerRoute =
  AdminOffboardingReasonManagerRouteImport.update({
    id: '/offboarding-reason-manager',
    path: '/offboarding-reason-manager',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLwfManagerRoute = AdminLwfManagerRouteImport.update({
  id: '/lwf-manager',
  path: '/lwf-manager',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLanguageManagerRoute = AdminLanguageManagerRouteImport.update({
  id: '/language-manager',
  path: '/language-manager',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExServiceManagerRoute = AdminExServiceManagerRouteImport.update({
  id: '/ex-service-manager',
  path: '/ex-service-manager',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEsicBranchManagerRoute = AdminEsicBranchManagerRouteImport.update({
  id: '/esic-branch-manager',
  path: '/esic-branch-manager',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmployeesRoute = AdminEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDutyManagerRoute = AdminDutyManagerRouteImport.update({
  id: '/duty-manager',
  path: '/duty-manager',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDesignationManagerRoute = AdminDesignationManagerRouteImport.update({
  id: '/designation-manager',
  path: '/designation-manager',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCostComponentManagerRoute =
  AdminCostComponentManagerRouteImport.update({
    id: '/cost-component-manager',
    path: '/cost-component-manager',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminControlCenterRoute = AdminControlCenterRouteImport.update({
  id: '/control-center',
  path: '/control-center',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCompanyDocumentsRoute = AdminCompanyDocumentsRouteImport.update({
  id: '/company-documents',
  path: '/company-documents',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBillingTypeManagerRoute = AdminBillingTypeManagerRouteImport.update({
  id: '/billing-type-manager',
  path: '/billing-type-manager',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAttendanceCodeManagerRoute =
  AdminAttendanceCodeManagerRouteImport.update({
    id: '/attendance-code-manager',
    path: '/attendance-code-manager',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAttendanceRoute = AdminAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssetManagerRoute = AdminAssetManagerRouteImport.update({
  id: '/asset-manager',
  path: '/asset-manager',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAllowanceManagerRoute = AdminAllowanceManagerRouteImport.update({
  id: '/allowance-manager',
  path: '/allowance-manager',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPayrollIndexRoute = AdminPayrollIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminPayrollRoute,
} as any)
const AdminAttendanceIndexRoute = AdminAttendanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAttendanceRoute,
} as any)
const AdminVehiclesServiceManagerRoute =
  AdminVehiclesServiceManagerRouteImport.update({
    id: '/service-manager',
    path: '/service-manager',
    getParentRoute: () => AdminVehiclesRoute,
  } as any)
const AdminVehiclesPucsRoute = AdminVehiclesPucsRouteImport.update({
  id: '/pucs',
  path: '/pucs',
  getParentRoute: () => AdminVehiclesRoute,
} as any)
const AdminVehiclesInventoryRoute = AdminVehiclesInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminVehiclesRoute,
} as any)
const AdminVehiclesInsurancesRoute = AdminVehiclesInsurancesRouteImport.update({
  id: '/insurances',
  path: '/insurances',
  getParentRoute: () => AdminVehiclesRoute,
} as any)
const AdminVehiclesInsightLabRoute = AdminVehiclesInsightLabRouteImport.update({
  id: '/insight-lab',
  path: '/insight-lab',
  getParentRoute: () => AdminVehiclesRoute,
} as any)
const AdminVehiclesFastagsRoute = AdminVehiclesFastagsRouteImport.update({
  id: '/fastags',
  path: '/fastags',
  getParentRoute: () => AdminVehiclesRoute,
} as any)
const AdminVehiclesExpenseManagerRoute =
  AdminVehiclesExpenseManagerRouteImport.update({
    id: '/expense-manager',
    path: '/expense-manager',
    getParentRoute: () => AdminVehiclesRoute,
  } as any)
const AdminPayrollUnitIdRoute = AdminPayrollUnitIdRouteImport.update({
  id: '/$unitId',
  path: '/$unitId',
  getParentRoute: () => AdminPayrollRoute,
} as any)
const AdminInventoryWriteOffsRoute = AdminInventoryWriteOffsRouteImport.update({
  id: '/write-offs',
  path: '/write-offs',
  getParentRoute: () => AdminInventoryRoute,
} as any)
const AdminInventoryWarehousesRoute =
  AdminInventoryWarehousesRouteImport.update({
    id: '/warehouses',
    path: '/warehouses',
    getParentRoute: () => AdminInventoryRoute,
  } as any)
const AdminInventoryVendorsRoute = AdminInventoryVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AdminInventoryRoute,
} as any)
const AdminInventoryTransfersRoute = AdminInventoryTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => AdminInventoryRoute,
} as any)
const AdminInventoryStockRoute = AdminInventoryStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AdminInventoryRoute,
} as any)
const AdminInventoryPurchaseOrdersRoute =
  AdminInventoryPurchaseOrdersRouteImport.update({
    id: '/purchase-orders',
    path: '/purchase-orders',
    getParentRoute: () => AdminInventoryRoute,
  } as any)
const AdminInventoryItemsRoute = AdminInventoryItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => AdminInventoryRoute,
} as any)
const AdminInventoryIssuancesRoute = AdminInventoryIssuancesRouteImport.update({
  id: '/issuances',
  path: '/issuances',
  getParentRoute: () => AdminInventoryRoute,
} as any)
const AdminInventoryGoodsReceiptsRoute =
  AdminInventoryGoodsReceiptsRouteImport.update({
    id: '/goods-receipts',
    path: '/goods-receipts',
    getParentRoute: () => AdminInventoryRoute,
  } as any)
const AdminInventoryDashboardRoute = AdminInventoryDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminInventoryRoute,
} as any)
const AdminInventoryAdjustmentsRoute =
  AdminInventoryAdjustmentsRouteImport.update({
    id: '/adjustments',
    path: '/adjustments',
    getParentRoute: () => AdminInventoryRoute,
  } as any)
const AdminCustomersUnitManagerRoute =
  AdminCustomersUnitManagerRouteImport.update({
    id: '/unit-manager',
    path: '/unit-manager',
    getParentRoute: () => AdminCustomersRoute,
  } as any)
const AdminCustomersStateManagerRoute =
  AdminCustomersStateManagerRouteImport.update({
    id: '/state-manager',
    path: '/state-manager',
    getParentRoute: () => AdminCustomersRoute,
  } as any)
const AdminCustomersCustomerManagerRoute =
  AdminCustomersCustomerManagerRouteImport.update({
    id: '/customer-manager',
    path: '/customer-manager',
    getParentRoute: () => AdminCustomersRoute,
  } as any)
const AdminCustomersBranchManagerRoute =
  AdminCustomersBranchManagerRouteImport.update({
    id: '/branch-manager',
    path: '/branch-manager',
    getParentRoute: () => AdminCustomersRoute,
  } as any)
const AdminContractsClientContractsRoute =
  AdminContractsClientContractsRouteImport.update({
    id: '/contracts/client-contracts',
    path: '/contracts/client-contracts',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAttendanceUnitIdRoute = AdminAttendanceUnitIdRouteImport.update({
  id: '/$unitId',
  path: '/$unitId',
  getParentRoute: () => AdminAttendanceRoute,
} as any)
const AdminCandidatesIdDetailsRoute =
  AdminCandidatesIdDetailsRouteImport.update({
    id: '/candidates/$id/details',
    path: '/candidates/$id/details',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/welcome': typeof WelcomeRoute
  '/admin/allowance-manager': typeof AdminAllowanceManagerRoute
  '/admin/asset-manager': typeof AdminAssetManagerRoute
  '/admin/attendance': typeof AdminAttendanceRouteWithChildren
  '/admin/attendance-code-manager': typeof AdminAttendanceCodeManagerRoute
  '/admin/billing-type-manager': typeof AdminBillingTypeManagerRoute
  '/admin/company-documents': typeof AdminCompanyDocumentsRoute
  '/admin/control-center': typeof AdminControlCenterRoute
  '/admin/cost-component-manager': typeof AdminCostComponentManagerRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/designation-manager': typeof AdminDesignationManagerRoute
  '/admin/duty-manager': typeof AdminDutyManagerRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/esic-branch-manager': typeof AdminEsicBranchManagerRoute
  '/admin/ex-service-manager': typeof AdminExServiceManagerRoute
  '/admin/inventory': typeof AdminInventoryRouteWithChildren
  '/admin/language-manager': typeof AdminLanguageManagerRoute
  '/admin/lwf-manager': typeof AdminLwfManagerRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/offboarding-reason-manager': typeof AdminOffboardingReasonManagerRoute
  '/admin/payroll': typeof AdminPayrollRouteWithChildren
  '/admin/payroll-days-manager': typeof AdminPayrollDaysManagerRoute
  '/admin/payroll-manager': typeof AdminPayrollManagerRoute
  '/admin/professional-tax-manager': typeof AdminProfessionalTaxManagerRoute
  '/admin/rbac': typeof AdminRbacRoute
  '/admin/service-type-manager': typeof AdminServiceTypeManagerRoute
  '/admin/system-logs': typeof AdminSystemLogsRoute
  '/admin/vehicles': typeof AdminVehiclesRouteWithChildren
  '/admin/attendance/$unitId': typeof AdminAttendanceUnitIdRoute
  '/admin/contracts/client-contracts': typeof AdminContractsClientContractsRoute
  '/admin/customers/branch-manager': typeof AdminCustomersBranchManagerRoute
  '/admin/customers/customer-manager': typeof AdminCustomersCustomerManagerRoute
  '/admin/customers/state-manager': typeof AdminCustomersStateManagerRoute
  '/admin/customers/unit-manager': typeof AdminCustomersUnitManagerRoute
  '/admin/inventory/adjustments': typeof AdminInventoryAdjustmentsRoute
  '/admin/inventory/dashboard': typeof AdminInventoryDashboardRoute
  '/admin/inventory/goods-receipts': typeof AdminInventoryGoodsReceiptsRoute
  '/admin/inventory/issuances': typeof AdminInventoryIssuancesRoute
  '/admin/inventory/items': typeof AdminInventoryItemsRoute
  '/admin/inventory/purchase-orders': typeof AdminInventoryPurchaseOrdersRoute
  '/admin/inventory/stock': typeof AdminInventoryStockRoute
  '/admin/inventory/transfers': typeof AdminInventoryTransfersRoute
  '/admin/inventory/vendors': typeof AdminInventoryVendorsRoute
  '/admin/inventory/warehouses': typeof AdminInventoryWarehousesRoute
  '/admin/inventory/write-offs': typeof AdminInventoryWriteOffsRoute
  '/admin/payroll/$unitId': typeof AdminPayrollUnitIdRoute
  '/admin/vehicles/expense-manager': typeof AdminVehiclesExpenseManagerRoute
  '/admin/vehicles/fastags': typeof AdminVehiclesFastagsRoute
  '/admin/vehicles/insight-lab': typeof AdminVehiclesInsightLabRoute
  '/admin/vehicles/insurances': typeof AdminVehiclesInsurancesRoute
  '/admin/vehicles/inventory': typeof AdminVehiclesInventoryRoute
  '/admin/vehicles/pucs': typeof AdminVehiclesPucsRoute
  '/admin/vehicles/service-manager': typeof AdminVehiclesServiceManagerRoute
  '/admin/attendance/': typeof AdminAttendanceIndexRoute
  '/admin/payroll/': typeof AdminPayrollIndexRoute
  '/admin/candidates/$id/details': typeof AdminCandidatesIdDetailsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/welcome': typeof WelcomeRoute
  '/admin/allowance-manager': typeof AdminAllowanceManagerRoute
  '/admin/asset-manager': typeof AdminAssetManagerRoute
  '/admin/attendance-code-manager': typeof AdminAttendanceCodeManagerRoute
  '/admin/billing-type-manager': typeof AdminBillingTypeManagerRoute
  '/admin/company-documents': typeof AdminCompanyDocumentsRoute
  '/admin/control-center': typeof AdminControlCenterRoute
  '/admin/cost-component-manager': typeof AdminCostComponentManagerRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/designation-manager': typeof AdminDesignationManagerRoute
  '/admin/duty-manager': typeof AdminDutyManagerRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/esic-branch-manager': typeof AdminEsicBranchManagerRoute
  '/admin/ex-service-manager': typeof AdminExServiceManagerRoute
  '/admin/inventory': typeof AdminInventoryRouteWithChildren
  '/admin/language-manager': typeof AdminLanguageManagerRoute
  '/admin/lwf-manager': typeof AdminLwfManagerRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/offboarding-reason-manager': typeof AdminOffboardingReasonManagerRoute
  '/admin/payroll-days-manager': typeof AdminPayrollDaysManagerRoute
  '/admin/payroll-manager': typeof AdminPayrollManagerRoute
  '/admin/professional-tax-manager': typeof AdminProfessionalTaxManagerRoute
  '/admin/rbac': typeof AdminRbacRoute
  '/admin/service-type-manager': typeof AdminServiceTypeManagerRoute
  '/admin/system-logs': typeof AdminSystemLogsRoute
  '/admin/vehicles': typeof AdminVehiclesRouteWithChildren
  '/admin/attendance/$unitId': typeof AdminAttendanceUnitIdRoute
  '/admin/contracts/client-contracts': typeof AdminContractsClientContractsRoute
  '/admin/customers/branch-manager': typeof AdminCustomersBranchManagerRoute
  '/admin/customers/customer-manager': typeof AdminCustomersCustomerManagerRoute
  '/admin/customers/state-manager': typeof AdminCustomersStateManagerRoute
  '/admin/customers/unit-manager': typeof AdminCustomersUnitManagerRoute
  '/admin/inventory/adjustments': typeof AdminInventoryAdjustmentsRoute
  '/admin/inventory/dashboard': typeof AdminInventoryDashboardRoute
  '/admin/inventory/goods-receipts': typeof AdminInventoryGoodsReceiptsRoute
  '/admin/inventory/issuances': typeof AdminInventoryIssuancesRoute
  '/admin/inventory/items': typeof AdminInventoryItemsRoute
  '/admin/inventory/purchase-orders': typeof AdminInventoryPurchaseOrdersRoute
  '/admin/inventory/stock': typeof AdminInventoryStockRoute
  '/admin/inventory/transfers': typeof AdminInventoryTransfersRoute
  '/admin/inventory/vendors': typeof AdminInventoryVendorsRoute
  '/admin/inventory/warehouses': typeof AdminInventoryWarehousesRoute
  '/admin/inventory/write-offs': typeof AdminInventoryWriteOffsRoute
  '/admin/payroll/$unitId': typeof AdminPayrollUnitIdRoute
  '/admin/vehicles/expense-manager': typeof AdminVehiclesExpenseManagerRoute
  '/admin/vehicles/fastags': typeof AdminVehiclesFastagsRoute
  '/admin/vehicles/insight-lab': typeof AdminVehiclesInsightLabRoute
  '/admin/vehicles/insurances': typeof AdminVehiclesInsurancesRoute
  '/admin/vehicles/inventory': typeof AdminVehiclesInventoryRoute
  '/admin/vehicles/pucs': typeof AdminVehiclesPucsRoute
  '/admin/vehicles/service-manager': typeof AdminVehiclesServiceManagerRoute
  '/admin/attendance': typeof AdminAttendanceIndexRoute
  '/admin/payroll': typeof AdminPayrollIndexRoute
  '/admin/candidates/$id/details': typeof AdminCandidatesIdDetailsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/welcome': typeof WelcomeRoute
  '/admin/allowance-manager': typeof AdminAllowanceManagerRoute
  '/admin/asset-manager': typeof AdminAssetManagerRoute
  '/admin/attendance': typeof AdminAttendanceRouteWithChildren
  '/admin/attendance-code-manager': typeof AdminAttendanceCodeManagerRoute
  '/admin/billing-type-manager': typeof AdminBillingTypeManagerRoute
  '/admin/company-documents': typeof AdminCompanyDocumentsRoute
  '/admin/control-center': typeof AdminControlCenterRoute
  '/admin/cost-component-manager': typeof AdminCostComponentManagerRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/designation-manager': typeof AdminDesignationManagerRoute
  '/admin/duty-manager': typeof AdminDutyManagerRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/esic-branch-manager': typeof AdminEsicBranchManagerRoute
  '/admin/ex-service-manager': typeof AdminExServiceManagerRoute
  '/admin/inventory': typeof AdminInventoryRouteWithChildren
  '/admin/language-manager': typeof AdminLanguageManagerRoute
  '/admin/lwf-manager': typeof AdminLwfManagerRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/offboarding-reason-manager': typeof AdminOffboardingReasonManagerRoute
  '/admin/payroll': typeof AdminPayrollRouteWithChildren
  '/admin/payroll-days-manager': typeof AdminPayrollDaysManagerRoute
  '/admin/payroll-manager': typeof AdminPayrollManagerRoute
  '/admin/professional-tax-manager': typeof AdminProfessionalTaxManagerRoute
  '/admin/rbac': typeof AdminRbacRoute
  '/admin/service-type-manager': typeof AdminServiceTypeManagerRoute
  '/admin/system-logs': typeof AdminSystemLogsRoute
  '/admin/vehicles': typeof AdminVehiclesRouteWithChildren
  '/admin/attendance/$unitId': typeof AdminAttendanceUnitIdRoute
  '/admin/contracts/client-contracts': typeof AdminContractsClientContractsRoute
  '/admin/customers/branch-manager': typeof AdminCustomersBranchManagerRoute
  '/admin/customers/customer-manager': typeof AdminCustomersCustomerManagerRoute
  '/admin/customers/state-manager': typeof AdminCustomersStateManagerRoute
  '/admin/customers/unit-manager': typeof AdminCustomersUnitManagerRoute
  '/admin/inventory/adjustments': typeof AdminInventoryAdjustmentsRoute
  '/admin/inventory/dashboard': typeof AdminInventoryDashboardRoute
  '/admin/inventory/goods-receipts': typeof AdminInventoryGoodsReceiptsRoute
  '/admin/inventory/issuances': typeof AdminInventoryIssuancesRoute
  '/admin/inventory/items': typeof AdminInventoryItemsRoute
  '/admin/inventory/purchase-orders': typeof AdminInventoryPurchaseOrdersRoute
  '/admin/inventory/stock': typeof AdminInventoryStockRoute
  '/admin/inventory/transfers': typeof AdminInventoryTransfersRoute
  '/admin/inventory/vendors': typeof AdminInventoryVendorsRoute
  '/admin/inventory/warehouses': typeof AdminInventoryWarehousesRoute
  '/admin/inventory/write-offs': typeof AdminInventoryWriteOffsRoute
  '/admin/payroll/$unitId': typeof AdminPayrollUnitIdRoute
  '/admin/vehicles/expense-manager': typeof AdminVehiclesExpenseManagerRoute
  '/admin/vehicles/fastags': typeof AdminVehiclesFastagsRoute
  '/admin/vehicles/insight-lab': typeof AdminVehiclesInsightLabRoute
  '/admin/vehicles/insurances': typeof AdminVehiclesInsurancesRoute
  '/admin/vehicles/inventory': typeof AdminVehiclesInventoryRoute
  '/admin/vehicles/pucs': typeof AdminVehiclesPucsRoute
  '/admin/vehicles/service-manager': typeof AdminVehiclesServiceManagerRoute
  '/admin/attendance/': typeof AdminAttendanceIndexRoute
  '/admin/payroll/': typeof AdminPayrollIndexRoute
  '/admin/candidates/$id/details': typeof AdminCandidatesIdDetailsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/welcome'
    | '/admin/allowance-manager'
    | '/admin/asset-manager'
    | '/admin/attendance'
    | '/admin/attendance-code-manager'
    | '/admin/billing-type-manager'
    | '/admin/company-documents'
    | '/admin/control-center'
    | '/admin/cost-component-manager'
    | '/admin/customers'
    | '/admin/designation-manager'
    | '/admin/duty-manager'
    | '/admin/employees'
    | '/admin/esic-branch-manager'
    | '/admin/ex-service-manager'
    | '/admin/inventory'
    | '/admin/language-manager'
    | '/admin/lwf-manager'
    | '/admin/notifications'
    | '/admin/offboarding-reason-manager'
    | '/admin/payroll'
    | '/admin/payroll-days-manager'
    | '/admin/payroll-manager'
    | '/admin/professional-tax-manager'
    | '/admin/rbac'
    | '/admin/service-type-manager'
    | '/admin/system-logs'
    | '/admin/vehicles'
    | '/admin/attendance/$unitId'
    | '/admin/contracts/client-contracts'
    | '/admin/customers/branch-manager'
    | '/admin/customers/customer-manager'
    | '/admin/customers/state-manager'
    | '/admin/customers/unit-manager'
    | '/admin/inventory/adjustments'
    | '/admin/inventory/dashboard'
    | '/admin/inventory/goods-receipts'
    | '/admin/inventory/issuances'
    | '/admin/inventory/items'
    | '/admin/inventory/purchase-orders'
    | '/admin/inventory/stock'
    | '/admin/inventory/transfers'
    | '/admin/inventory/vendors'
    | '/admin/inventory/warehouses'
    | '/admin/inventory/write-offs'
    | '/admin/payroll/$unitId'
    | '/admin/vehicles/expense-manager'
    | '/admin/vehicles/fastags'
    | '/admin/vehicles/insight-lab'
    | '/admin/vehicles/insurances'
    | '/admin/vehicles/inventory'
    | '/admin/vehicles/pucs'
    | '/admin/vehicles/service-manager'
    | '/admin/attendance/'
    | '/admin/payroll/'
    | '/admin/candidates/$id/details'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/welcome'
    | '/admin/allowance-manager'
    | '/admin/asset-manager'
    | '/admin/attendance-code-manager'
    | '/admin/billing-type-manager'
    | '/admin/company-documents'
    | '/admin/control-center'
    | '/admin/cost-component-manager'
    | '/admin/customers'
    | '/admin/designation-manager'
    | '/admin/duty-manager'
    | '/admin/employees'
    | '/admin/esic-branch-manager'
    | '/admin/ex-service-manager'
    | '/admin/inventory'
    | '/admin/language-manager'
    | '/admin/lwf-manager'
    | '/admin/notifications'
    | '/admin/offboarding-reason-manager'
    | '/admin/payroll-days-manager'
    | '/admin/payroll-manager'
    | '/admin/professional-tax-manager'
    | '/admin/rbac'
    | '/admin/service-type-manager'
    | '/admin/system-logs'
    | '/admin/vehicles'
    | '/admin/attendance/$unitId'
    | '/admin/contracts/client-contracts'
    | '/admin/customers/branch-manager'
    | '/admin/customers/customer-manager'
    | '/admin/customers/state-manager'
    | '/admin/customers/unit-manager'
    | '/admin/inventory/adjustments'
    | '/admin/inventory/dashboard'
    | '/admin/inventory/goods-receipts'
    | '/admin/inventory/issuances'
    | '/admin/inventory/items'
    | '/admin/inventory/purchase-orders'
    | '/admin/inventory/stock'
    | '/admin/inventory/transfers'
    | '/admin/inventory/vendors'
    | '/admin/inventory/warehouses'
    | '/admin/inventory/write-offs'
    | '/admin/payroll/$unitId'
    | '/admin/vehicles/expense-manager'
    | '/admin/vehicles/fastags'
    | '/admin/vehicles/insight-lab'
    | '/admin/vehicles/insurances'
    | '/admin/vehicles/inventory'
    | '/admin/vehicles/pucs'
    | '/admin/vehicles/service-manager'
    | '/admin/attendance'
    | '/admin/payroll'
    | '/admin/candidates/$id/details'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/welcome'
    | '/admin/allowance-manager'
    | '/admin/asset-manager'
    | '/admin/attendance'
    | '/admin/attendance-code-manager'
    | '/admin/billing-type-manager'
    | '/admin/company-documents'
    | '/admin/control-center'
    | '/admin/cost-component-manager'
    | '/admin/customers'
    | '/admin/designation-manager'
    | '/admin/duty-manager'
    | '/admin/employees'
    | '/admin/esic-branch-manager'
    | '/admin/ex-service-manager'
    | '/admin/inventory'
    | '/admin/language-manager'
    | '/admin/lwf-manager'
    | '/admin/notifications'
    | '/admin/offboarding-reason-manager'
    | '/admin/payroll'
    | '/admin/payroll-days-manager'
    | '/admin/payroll-manager'
    | '/admin/professional-tax-manager'
    | '/admin/rbac'
    | '/admin/service-type-manager'
    | '/admin/system-logs'
    | '/admin/vehicles'
    | '/admin/attendance/$unitId'
    | '/admin/contracts/client-contracts'
    | '/admin/customers/branch-manager'
    | '/admin/customers/customer-manager'
    | '/admin/customers/state-manager'
    | '/admin/customers/unit-manager'
    | '/admin/inventory/adjustments'
    | '/admin/inventory/dashboard'
    | '/admin/inventory/goods-receipts'
    | '/admin/inventory/issuances'
    | '/admin/inventory/items'
    | '/admin/inventory/purchase-orders'
    | '/admin/inventory/stock'
    | '/admin/inventory/transfers'
    | '/admin/inventory/vendors'
    | '/admin/inventory/warehouses'
    | '/admin/inventory/write-offs'
    | '/admin/payroll/$unitId'
    | '/admin/vehicles/expense-manager'
    | '/admin/vehicles/fastags'
    | '/admin/vehicles/insight-lab'
    | '/admin/vehicles/insurances'
    | '/admin/vehicles/inventory'
    | '/admin/vehicles/pucs'
    | '/admin/vehicles/service-manager'
    | '/admin/attendance/'
    | '/admin/payroll/'
    | '/admin/candidates/$id/details'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vehicles': {
      id: '/admin/vehicles'
      path: '/vehicles'
      fullPath: '/admin/vehicles'
      preLoaderRoute: typeof AdminVehiclesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system-logs': {
      id: '/admin/system-logs'
      path: '/system-logs'
      fullPath: '/admin/system-logs'
      preLoaderRoute: typeof AdminSystemLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/service-type-manager': {
      id: '/admin/service-type-manager'
      path: '/service-type-manager'
      fullPath: '/admin/service-type-manager'
      preLoaderRoute: typeof AdminServiceTypeManagerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rbac': {
      id: '/admin/rbac'
      path: '/rbac'
      fullPath: '/admin/rbac'
      preLoaderRoute: typeof AdminRbacRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/professional-tax-manager': {
      id: '/admin/professional-tax-manager'
      path: '/professional-tax-manager'
      fullPath: '/admin/professional-tax-manager'
      preLoaderRoute: typeof AdminProfessionalTaxManagerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payroll-manager': {
      id: '/admin/payroll-manager'
      path: '/payroll-manager'
      fullPath: '/admin/payroll-manager'
      preLoaderRoute: typeof AdminPayrollManagerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payroll-days-manager': {
      id: '/admin/payroll-days-manager'
      path: '/payroll-days-manager'
      fullPath: '/admin/payroll-days-manager'
      preLoaderRoute: typeof AdminPayrollDaysManagerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payroll': {
      id: '/admin/payroll'
      path: '/payroll'
      fullPath: '/admin/payroll'
      preLoaderRoute: typeof AdminPayrollRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/offboarding-reason-manager': {
      id: '/admin/offboarding-reason-manager'
      path: '/offboarding-reason-manager'
      fullPath: '/admin/offboarding-reason-manager'
      preLoaderRoute: typeof AdminOffboardingReasonManagerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lwf-manager': {
      id: '/admin/lwf-manager'
      path: '/lwf-manager'
      fullPath: '/admin/lwf-manager'
      preLoaderRoute: typeof AdminLwfManagerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/language-manager': {
      id: '/admin/language-manager'
      path: '/language-manager'
      fullPath: '/admin/language-manager'
      preLoaderRoute: typeof AdminLanguageManagerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ex-service-manager': {
      id: '/admin/ex-service-manager'
      path: '/ex-service-manager'
      fullPath: '/admin/ex-service-manager'
      preLoaderRoute: typeof AdminExServiceManagerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/esic-branch-manager': {
      id: '/admin/esic-branch-manager'
      path: '/esic-branch-manager'
      fullPath: '/admin/esic-branch-manager'
      preLoaderRoute: typeof AdminEsicBranchManagerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/employees': {
      id: '/admin/employees'
      path: '/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AdminEmployeesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/duty-manager': {
      id: '/admin/duty-manager'
      path: '/duty-manager'
      fullPath: '/admin/duty-manager'
      preLoaderRoute: typeof AdminDutyManagerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/designation-manager': {
      id: '/admin/designation-manager'
      path: '/designation-manager'
      fullPath: '/admin/designation-manager'
      preLoaderRoute: typeof AdminDesignationManagerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cost-component-manager': {
      id: '/admin/cost-component-manager'
      path: '/cost-component-manager'
      fullPath: '/admin/cost-component-manager'
      preLoaderRoute: typeof AdminCostComponentManagerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/control-center': {
      id: '/admin/control-center'
      path: '/control-center'
      fullPath: '/admin/control-center'
      preLoaderRoute: typeof AdminControlCenterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/company-documents': {
      id: '/admin/company-documents'
      path: '/company-documents'
      fullPath: '/admin/company-documents'
      preLoaderRoute: typeof AdminCompanyDocumentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/billing-type-manager': {
      id: '/admin/billing-type-manager'
      path: '/billing-type-manager'
      fullPath: '/admin/billing-type-manager'
      preLoaderRoute: typeof AdminBillingTypeManagerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/attendance-code-manager': {
      id: '/admin/attendance-code-manager'
      path: '/attendance-code-manager'
      fullPath: '/admin/attendance-code-manager'
      preLoaderRoute: typeof AdminAttendanceCodeManagerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/attendance': {
      id: '/admin/attendance'
      path: '/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AdminAttendanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/asset-manager': {
      id: '/admin/asset-manager'
      path: '/asset-manager'
      fullPath: '/admin/asset-manager'
      preLoaderRoute: typeof AdminAssetManagerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/allowance-manager': {
      id: '/admin/allowance-manager'
      path: '/allowance-manager'
      fullPath: '/admin/allowance-manager'
      preLoaderRoute: typeof AdminAllowanceManagerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payroll/': {
      id: '/admin/payroll/'
      path: '/'
      fullPath: '/admin/payroll/'
      preLoaderRoute: typeof AdminPayrollIndexRouteImport
      parentRoute: typeof AdminPayrollRoute
    }
    '/admin/attendance/': {
      id: '/admin/attendance/'
      path: '/'
      fullPath: '/admin/attendance/'
      preLoaderRoute: typeof AdminAttendanceIndexRouteImport
      parentRoute: typeof AdminAttendanceRoute
    }
    '/admin/vehicles/service-manager': {
      id: '/admin/vehicles/service-manager'
      path: '/service-manager'
      fullPath: '/admin/vehicles/service-manager'
      preLoaderRoute: typeof AdminVehiclesServiceManagerRouteImport
      parentRoute: typeof AdminVehiclesRoute
    }
    '/admin/vehicles/pucs': {
      id: '/admin/vehicles/pucs'
      path: '/pucs'
      fullPath: '/admin/vehicles/pucs'
      preLoaderRoute: typeof AdminVehiclesPucsRouteImport
      parentRoute: typeof AdminVehiclesRoute
    }
    '/admin/vehicles/inventory': {
      id: '/admin/vehicles/inventory'
      path: '/inventory'
      fullPath: '/admin/vehicles/inventory'
      preLoaderRoute: typeof AdminVehiclesInventoryRouteImport
      parentRoute: typeof AdminVehiclesRoute
    }
    '/admin/vehicles/insurances': {
      id: '/admin/vehicles/insurances'
      path: '/insurances'
      fullPath: '/admin/vehicles/insurances'
      preLoaderRoute: typeof AdminVehiclesInsurancesRouteImport
      parentRoute: typeof AdminVehiclesRoute
    }
    '/admin/vehicles/insight-lab': {
      id: '/admin/vehicles/insight-lab'
      path: '/insight-lab'
      fullPath: '/admin/vehicles/insight-lab'
      preLoaderRoute: typeof AdminVehiclesInsightLabRouteImport
      parentRoute: typeof AdminVehiclesRoute
    }
    '/admin/vehicles/fastags': {
      id: '/admin/vehicles/fastags'
      path: '/fastags'
      fullPath: '/admin/vehicles/fastags'
      preLoaderRoute: typeof AdminVehiclesFastagsRouteImport
      parentRoute: typeof AdminVehiclesRoute
    }
    '/admin/vehicles/expense-manager': {
      id: '/admin/vehicles/expense-manager'
      path: '/expense-manager'
      fullPath: '/admin/vehicles/expense-manager'
      preLoaderRoute: typeof AdminVehiclesExpenseManagerRouteImport
      parentRoute: typeof AdminVehiclesRoute
    }
    '/admin/payroll/$unitId': {
      id: '/admin/payroll/$unitId'
      path: '/$unitId'
      fullPath: '/admin/payroll/$unitId'
      preLoaderRoute: typeof AdminPayrollUnitIdRouteImport
      parentRoute: typeof AdminPayrollRoute
    }
    '/admin/inventory/write-offs': {
      id: '/admin/inventory/write-offs'
      path: '/write-offs'
      fullPath: '/admin/inventory/write-offs'
      preLoaderRoute: typeof AdminInventoryWriteOffsRouteImport
      parentRoute: typeof AdminInventoryRoute
    }
    '/admin/inventory/warehouses': {
      id: '/admin/inventory/warehouses'
      path: '/warehouses'
      fullPath: '/admin/inventory/warehouses'
      preLoaderRoute: typeof AdminInventoryWarehousesRouteImport
      parentRoute: typeof AdminInventoryRoute
    }
    '/admin/inventory/vendors': {
      id: '/admin/inventory/vendors'
      path: '/vendors'
      fullPath: '/admin/inventory/vendors'
      preLoaderRoute: typeof AdminInventoryVendorsRouteImport
      parentRoute: typeof AdminInventoryRoute
    }
    '/admin/inventory/transfers': {
      id: '/admin/inventory/transfers'
      path: '/transfers'
      fullPath: '/admin/inventory/transfers'
      preLoaderRoute: typeof AdminInventoryTransfersRouteImport
      parentRoute: typeof AdminInventoryRoute
    }
    '/admin/inventory/stock': {
      id: '/admin/inventory/stock'
      path: '/stock'
      fullPath: '/admin/inventory/stock'
      preLoaderRoute: typeof AdminInventoryStockRouteImport
      parentRoute: typeof AdminInventoryRoute
    }
    '/admin/inventory/purchase-orders': {
      id: '/admin/inventory/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/admin/inventory/purchase-orders'
      preLoaderRoute: typeof AdminInventoryPurchaseOrdersRouteImport
      parentRoute: typeof AdminInventoryRoute
    }
    '/admin/inventory/items': {
      id: '/admin/inventory/items'
      path: '/items'
      fullPath: '/admin/inventory/items'
      preLoaderRoute: typeof AdminInventoryItemsRouteImport
      parentRoute: typeof AdminInventoryRoute
    }
    '/admin/inventory/issuances': {
      id: '/admin/inventory/issuances'
      path: '/issuances'
      fullPath: '/admin/inventory/issuances'
      preLoaderRoute: typeof AdminInventoryIssuancesRouteImport
      parentRoute: typeof AdminInventoryRoute
    }
    '/admin/inventory/goods-receipts': {
      id: '/admin/inventory/goods-receipts'
      path: '/goods-receipts'
      fullPath: '/admin/inventory/goods-receipts'
      preLoaderRoute: typeof AdminInventoryGoodsReceiptsRouteImport
      parentRoute: typeof AdminInventoryRoute
    }
    '/admin/inventory/dashboard': {
      id: '/admin/inventory/dashboard'
      path: '/dashboard'
      fullPath: '/admin/inventory/dashboard'
      preLoaderRoute: typeof AdminInventoryDashboardRouteImport
      parentRoute: typeof AdminInventoryRoute
    }
    '/admin/inventory/adjustments': {
      id: '/admin/inventory/adjustments'
      path: '/adjustments'
      fullPath: '/admin/inventory/adjustments'
      preLoaderRoute: typeof AdminInventoryAdjustmentsRouteImport
      parentRoute: typeof AdminInventoryRoute
    }
    '/admin/customers/unit-manager': {
      id: '/admin/customers/unit-manager'
      path: '/unit-manager'
      fullPath: '/admin/customers/unit-manager'
      preLoaderRoute: typeof AdminCustomersUnitManagerRouteImport
      parentRoute: typeof AdminCustomersRoute
    }
    '/admin/customers/state-manager': {
      id: '/admin/customers/state-manager'
      path: '/state-manager'
      fullPath: '/admin/customers/state-manager'
      preLoaderRoute: typeof AdminCustomersStateManagerRouteImport
      parentRoute: typeof AdminCustomersRoute
    }
    '/admin/customers/customer-manager': {
      id: '/admin/customers/customer-manager'
      path: '/customer-manager'
      fullPath: '/admin/customers/customer-manager'
      preLoaderRoute: typeof AdminCustomersCustomerManagerRouteImport
      parentRoute: typeof AdminCustomersRoute
    }
    '/admin/customers/branch-manager': {
      id: '/admin/customers/branch-manager'
      path: '/branch-manager'
      fullPath: '/admin/customers/branch-manager'
      preLoaderRoute: typeof AdminCustomersBranchManagerRouteImport
      parentRoute: typeof AdminCustomersRoute
    }
    '/admin/contracts/client-contracts': {
      id: '/admin/contracts/client-contracts'
      path: '/contracts/client-contracts'
      fullPath: '/admin/contracts/client-contracts'
      preLoaderRoute: typeof AdminContractsClientContractsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/attendance/$unitId': {
      id: '/admin/attendance/$unitId'
      path: '/$unitId'
      fullPath: '/admin/attendance/$unitId'
      preLoaderRoute: typeof AdminAttendanceUnitIdRouteImport
      parentRoute: typeof AdminAttendanceRoute
    }
    '/admin/candidates/$id/details': {
      id: '/admin/candidates/$id/details'
      path: '/candidates/$id/details'
      fullPath: '/admin/candidates/$id/details'
      preLoaderRoute: typeof AdminCandidatesIdDetailsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminAttendanceRouteChildren {
  AdminAttendanceUnitIdRoute: typeof AdminAttendanceUnitIdRoute
  AdminAttendanceIndexRoute: typeof AdminAttendanceIndexRoute
}

const AdminAttendanceRouteChildren: AdminAttendanceRouteChildren = {
  AdminAttendanceUnitIdRoute: AdminAttendanceUnitIdRoute,
  AdminAttendanceIndexRoute: AdminAttendanceIndexRoute,
}

const AdminAttendanceRouteWithChildren = AdminAttendanceRoute._addFileChildren(
  AdminAttendanceRouteChildren,
)

interface AdminCustomersRouteChildren {
  AdminCustomersBranchManagerRoute: typeof AdminCustomersBranchManagerRoute
  AdminCustomersCustomerManagerRoute: typeof AdminCustomersCustomerManagerRoute
  AdminCustomersStateManagerRoute: typeof AdminCustomersStateManagerRoute
  AdminCustomersUnitManagerRoute: typeof AdminCustomersUnitManagerRoute
}

const AdminCustomersRouteChildren: AdminCustomersRouteChildren = {
  AdminCustomersBranchManagerRoute: AdminCustomersBranchManagerRoute,
  AdminCustomersCustomerManagerRoute: AdminCustomersCustomerManagerRoute,
  AdminCustomersStateManagerRoute: AdminCustomersStateManagerRoute,
  AdminCustomersUnitManagerRoute: AdminCustomersUnitManagerRoute,
}

const AdminCustomersRouteWithChildren = AdminCustomersRoute._addFileChildren(
  AdminCustomersRouteChildren,
)

interface AdminInventoryRouteChildren {
  AdminInventoryAdjustmentsRoute: typeof AdminInventoryAdjustmentsRoute
  AdminInventoryDashboardRoute: typeof AdminInventoryDashboardRoute
  AdminInventoryGoodsReceiptsRoute: typeof AdminInventoryGoodsReceiptsRoute
  AdminInventoryIssuancesRoute: typeof AdminInventoryIssuancesRoute
  AdminInventoryItemsRoute: typeof AdminInventoryItemsRoute
  AdminInventoryPurchaseOrdersRoute: typeof AdminInventoryPurchaseOrdersRoute
  AdminInventoryStockRoute: typeof AdminInventoryStockRoute
  AdminInventoryTransfersRoute: typeof AdminInventoryTransfersRoute
  AdminInventoryVendorsRoute: typeof AdminInventoryVendorsRoute
  AdminInventoryWarehousesRoute: typeof AdminInventoryWarehousesRoute
  AdminInventoryWriteOffsRoute: typeof AdminInventoryWriteOffsRoute
}

const AdminInventoryRouteChildren: AdminInventoryRouteChildren = {
  AdminInventoryAdjustmentsRoute: AdminInventoryAdjustmentsRoute,
  AdminInventoryDashboardRoute: AdminInventoryDashboardRoute,
  AdminInventoryGoodsReceiptsRoute: AdminInventoryGoodsReceiptsRoute,
  AdminInventoryIssuancesRoute: AdminInventoryIssuancesRoute,
  AdminInventoryItemsRoute: AdminInventoryItemsRoute,
  AdminInventoryPurchaseOrdersRoute: AdminInventoryPurchaseOrdersRoute,
  AdminInventoryStockRoute: AdminInventoryStockRoute,
  AdminInventoryTransfersRoute: AdminInventoryTransfersRoute,
  AdminInventoryVendorsRoute: AdminInventoryVendorsRoute,
  AdminInventoryWarehousesRoute: AdminInventoryWarehousesRoute,
  AdminInventoryWriteOffsRoute: AdminInventoryWriteOffsRoute,
}

const AdminInventoryRouteWithChildren = AdminInventoryRoute._addFileChildren(
  AdminInventoryRouteChildren,
)

interface AdminPayrollRouteChildren {
  AdminPayrollUnitIdRoute: typeof AdminPayrollUnitIdRoute
  AdminPayrollIndexRoute: typeof AdminPayrollIndexRoute
}

const AdminPayrollRouteChildren: AdminPayrollRouteChildren = {
  AdminPayrollUnitIdRoute: AdminPayrollUnitIdRoute,
  AdminPayrollIndexRoute: AdminPayrollIndexRoute,
}

const AdminPayrollRouteWithChildren = AdminPayrollRoute._addFileChildren(
  AdminPayrollRouteChildren,
)

interface AdminVehiclesRouteChildren {
  AdminVehiclesExpenseManagerRoute: typeof AdminVehiclesExpenseManagerRoute
  AdminVehiclesFastagsRoute: typeof AdminVehiclesFastagsRoute
  AdminVehiclesInsightLabRoute: typeof AdminVehiclesInsightLabRoute
  AdminVehiclesInsurancesRoute: typeof AdminVehiclesInsurancesRoute
  AdminVehiclesInventoryRoute: typeof AdminVehiclesInventoryRoute
  AdminVehiclesPucsRoute: typeof AdminVehiclesPucsRoute
  AdminVehiclesServiceManagerRoute: typeof AdminVehiclesServiceManagerRoute
}

const AdminVehiclesRouteChildren: AdminVehiclesRouteChildren = {
  AdminVehiclesExpenseManagerRoute: AdminVehiclesExpenseManagerRoute,
  AdminVehiclesFastagsRoute: AdminVehiclesFastagsRoute,
  AdminVehiclesInsightLabRoute: AdminVehiclesInsightLabRoute,
  AdminVehiclesInsurancesRoute: AdminVehiclesInsurancesRoute,
  AdminVehiclesInventoryRoute: AdminVehiclesInventoryRoute,
  AdminVehiclesPucsRoute: AdminVehiclesPucsRoute,
  AdminVehiclesServiceManagerRoute: AdminVehiclesServiceManagerRoute,
}

const AdminVehiclesRouteWithChildren = AdminVehiclesRoute._addFileChildren(
  AdminVehiclesRouteChildren,
)

interface AdminRouteChildren {
  AdminAllowanceManagerRoute: typeof AdminAllowanceManagerRoute
  AdminAssetManagerRoute: typeof AdminAssetManagerRoute
  AdminAttendanceRoute: typeof AdminAttendanceRouteWithChildren
  AdminAttendanceCodeManagerRoute: typeof AdminAttendanceCodeManagerRoute
  AdminBillingTypeManagerRoute: typeof AdminBillingTypeManagerRoute
  AdminCompanyDocumentsRoute: typeof AdminCompanyDocumentsRoute
  AdminControlCenterRoute: typeof AdminControlCenterRoute
  AdminCostComponentManagerRoute: typeof AdminCostComponentManagerRoute
  AdminCustomersRoute: typeof AdminCustomersRouteWithChildren
  AdminDesignationManagerRoute: typeof AdminDesignationManagerRoute
  AdminDutyManagerRoute: typeof AdminDutyManagerRoute
  AdminEmployeesRoute: typeof AdminEmployeesRoute
  AdminEsicBranchManagerRoute: typeof AdminEsicBranchManagerRoute
  AdminExServiceManagerRoute: typeof AdminExServiceManagerRoute
  AdminInventoryRoute: typeof AdminInventoryRouteWithChildren
  AdminLanguageManagerRoute: typeof AdminLanguageManagerRoute
  AdminLwfManagerRoute: typeof AdminLwfManagerRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminOffboardingReasonManagerRoute: typeof AdminOffboardingReasonManagerRoute
  AdminPayrollRoute: typeof AdminPayrollRouteWithChildren
  AdminPayrollDaysManagerRoute: typeof AdminPayrollDaysManagerRoute
  AdminPayrollManagerRoute: typeof AdminPayrollManagerRoute
  AdminProfessionalTaxManagerRoute: typeof AdminProfessionalTaxManagerRoute
  AdminRbacRoute: typeof AdminRbacRoute
  AdminServiceTypeManagerRoute: typeof AdminServiceTypeManagerRoute
  AdminSystemLogsRoute: typeof AdminSystemLogsRoute
  AdminVehiclesRoute: typeof AdminVehiclesRouteWithChildren
  AdminContractsClientContractsRoute: typeof AdminContractsClientContractsRoute
  AdminCandidatesIdDetailsRoute: typeof AdminCandidatesIdDetailsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAllowanceManagerRoute: AdminAllowanceManagerRoute,
  AdminAssetManagerRoute: AdminAssetManagerRoute,
  AdminAttendanceRoute: AdminAttendanceRouteWithChildren,
  AdminAttendanceCodeManagerRoute: AdminAttendanceCodeManagerRoute,
  AdminBillingTypeManagerRoute: AdminBillingTypeManagerRoute,
  AdminCompanyDocumentsRoute: AdminCompanyDocumentsRoute,
  AdminControlCenterRoute: AdminControlCenterRoute,
  AdminCostComponentManagerRoute: AdminCostComponentManagerRoute,
  AdminCustomersRoute: AdminCustomersRouteWithChildren,
  AdminDesignationManagerRoute: AdminDesignationManagerRoute,
  AdminDutyManagerRoute: AdminDutyManagerRoute,
  AdminEmployeesRoute: AdminEmployeesRoute,
  AdminEsicBranchManagerRoute: AdminEsicBranchManagerRoute,
  AdminExServiceManagerRoute: AdminExServiceManagerRoute,
  AdminInventoryRoute: AdminInventoryRouteWithChildren,
  AdminLanguageManagerRoute: AdminLanguageManagerRoute,
  AdminLwfManagerRoute: AdminLwfManagerRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminOffboardingReasonManagerRoute: AdminOffboardingReasonManagerRoute,
  AdminPayrollRoute: AdminPayrollRouteWithChildren,
  AdminPayrollDaysManagerRoute: AdminPayrollDaysManagerRoute,
  AdminPayrollManagerRoute: AdminPayrollManagerRoute,
  AdminProfessionalTaxManagerRoute: AdminProfessionalTaxManagerRoute,
  AdminRbacRoute: AdminRbacRoute,
  AdminServiceTypeManagerRoute: AdminServiceTypeManagerRoute,
  AdminSystemLogsRoute: AdminSystemLogsRoute,
  AdminVehiclesRoute: AdminVehiclesRouteWithChildren,
  AdminContractsClientContractsRoute: AdminContractsClientContractsRoute,
  AdminCandidatesIdDetailsRoute: AdminCandidatesIdDetailsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
