/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminServiceTypeManagerRouteImport } from './routes/admin.service-type-manager'
import { Route as AdminProfessionalTaxManagerRouteImport } from './routes/admin.professional-tax-manager'
import { Route as AdminPayrollManagerRouteImport } from './routes/admin.payroll-manager'
import { Route as AdminLwfManagerRouteImport } from './routes/admin.lwf-manager'
import { Route as AdminDutyManagerRouteImport } from './routes/admin.duty-manager'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminControlCenterRouteImport } from './routes/admin.control-center'
import { Route as AdminBillingTypeManagerRouteImport } from './routes/admin.billing-type-manager'
import { Route as AdminAllowanceManagerRouteImport } from './routes/admin.allowance-manager'
import { Route as AdminCustomersUnitManagerRouteImport } from './routes/admin.customers.unit-manager'
import { Route as AdminCustomersStateManagerRouteImport } from './routes/admin.customers.state-manager'
import { Route as AdminCustomersCustomerManagerRouteImport } from './routes/admin.customers.customer-manager'
import { Route as AdminCustomersBranchManagerRouteImport } from './routes/admin.customers.branch-manager'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminServiceTypeManagerRoute = AdminServiceTypeManagerRouteImport.update({
  id: '/service-type-manager',
  path: '/service-type-manager',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfessionalTaxManagerRoute =
  AdminProfessionalTaxManagerRouteImport.update({
    id: '/professional-tax-manager',
    path: '/professional-tax-manager',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminPayrollManagerRoute = AdminPayrollManagerRouteImport.update({
  id: '/payroll-manager',
  path: '/payroll-manager',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLwfManagerRoute = AdminLwfManagerRouteImport.update({
  id: '/lwf-manager',
  path: '/lwf-manager',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDutyManagerRoute = AdminDutyManagerRouteImport.update({
  id: '/duty-manager',
  path: '/duty-manager',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminControlCenterRoute = AdminControlCenterRouteImport.update({
  id: '/control-center',
  path: '/control-center',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBillingTypeManagerRoute = AdminBillingTypeManagerRouteImport.update({
  id: '/billing-type-manager',
  path: '/billing-type-manager',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAllowanceManagerRoute = AdminAllowanceManagerRouteImport.update({
  id: '/allowance-manager',
  path: '/allowance-manager',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersUnitManagerRoute =
  AdminCustomersUnitManagerRouteImport.update({
    id: '/unit-manager',
    path: '/unit-manager',
    getParentRoute: () => AdminCustomersRoute,
  } as any)
const AdminCustomersStateManagerRoute =
  AdminCustomersStateManagerRouteImport.update({
    id: '/state-manager',
    path: '/state-manager',
    getParentRoute: () => AdminCustomersRoute,
  } as any)
const AdminCustomersCustomerManagerRoute =
  AdminCustomersCustomerManagerRouteImport.update({
    id: '/customer-manager',
    path: '/customer-manager',
    getParentRoute: () => AdminCustomersRoute,
  } as any)
const AdminCustomersBranchManagerRoute =
  AdminCustomersBranchManagerRouteImport.update({
    id: '/branch-manager',
    path: '/branch-manager',
    getParentRoute: () => AdminCustomersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/welcome': typeof WelcomeRoute
  '/admin/allowance-manager': typeof AdminAllowanceManagerRoute
  '/admin/billing-type-manager': typeof AdminBillingTypeManagerRoute
  '/admin/control-center': typeof AdminControlCenterRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/duty-manager': typeof AdminDutyManagerRoute
  '/admin/lwf-manager': typeof AdminLwfManagerRoute
  '/admin/payroll-manager': typeof AdminPayrollManagerRoute
  '/admin/professional-tax-manager': typeof AdminProfessionalTaxManagerRoute
  '/admin/service-type-manager': typeof AdminServiceTypeManagerRoute
  '/admin/customers/branch-manager': typeof AdminCustomersBranchManagerRoute
  '/admin/customers/customer-manager': typeof AdminCustomersCustomerManagerRoute
  '/admin/customers/state-manager': typeof AdminCustomersStateManagerRoute
  '/admin/customers/unit-manager': typeof AdminCustomersUnitManagerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/welcome': typeof WelcomeRoute
  '/admin/allowance-manager': typeof AdminAllowanceManagerRoute
  '/admin/billing-type-manager': typeof AdminBillingTypeManagerRoute
  '/admin/control-center': typeof AdminControlCenterRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/duty-manager': typeof AdminDutyManagerRoute
  '/admin/lwf-manager': typeof AdminLwfManagerRoute
  '/admin/payroll-manager': typeof AdminPayrollManagerRoute
  '/admin/professional-tax-manager': typeof AdminProfessionalTaxManagerRoute
  '/admin/service-type-manager': typeof AdminServiceTypeManagerRoute
  '/admin/customers/branch-manager': typeof AdminCustomersBranchManagerRoute
  '/admin/customers/customer-manager': typeof AdminCustomersCustomerManagerRoute
  '/admin/customers/state-manager': typeof AdminCustomersStateManagerRoute
  '/admin/customers/unit-manager': typeof AdminCustomersUnitManagerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/welcome': typeof WelcomeRoute
  '/admin/allowance-manager': typeof AdminAllowanceManagerRoute
  '/admin/billing-type-manager': typeof AdminBillingTypeManagerRoute
  '/admin/control-center': typeof AdminControlCenterRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/duty-manager': typeof AdminDutyManagerRoute
  '/admin/lwf-manager': typeof AdminLwfManagerRoute
  '/admin/payroll-manager': typeof AdminPayrollManagerRoute
  '/admin/professional-tax-manager': typeof AdminProfessionalTaxManagerRoute
  '/admin/service-type-manager': typeof AdminServiceTypeManagerRoute
  '/admin/customers/branch-manager': typeof AdminCustomersBranchManagerRoute
  '/admin/customers/customer-manager': typeof AdminCustomersCustomerManagerRoute
  '/admin/customers/state-manager': typeof AdminCustomersStateManagerRoute
  '/admin/customers/unit-manager': typeof AdminCustomersUnitManagerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/welcome'
    | '/admin/allowance-manager'
    | '/admin/billing-type-manager'
    | '/admin/control-center'
    | '/admin/customers'
    | '/admin/duty-manager'
    | '/admin/lwf-manager'
    | '/admin/payroll-manager'
    | '/admin/professional-tax-manager'
    | '/admin/service-type-manager'
    | '/admin/customers/branch-manager'
    | '/admin/customers/customer-manager'
    | '/admin/customers/state-manager'
    | '/admin/customers/unit-manager'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/welcome'
    | '/admin/allowance-manager'
    | '/admin/billing-type-manager'
    | '/admin/control-center'
    | '/admin/customers'
    | '/admin/duty-manager'
    | '/admin/lwf-manager'
    | '/admin/payroll-manager'
    | '/admin/professional-tax-manager'
    | '/admin/service-type-manager'
    | '/admin/customers/branch-manager'
    | '/admin/customers/customer-manager'
    | '/admin/customers/state-manager'
    | '/admin/customers/unit-manager'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/welcome'
    | '/admin/allowance-manager'
    | '/admin/billing-type-manager'
    | '/admin/control-center'
    | '/admin/customers'
    | '/admin/duty-manager'
    | '/admin/lwf-manager'
    | '/admin/payroll-manager'
    | '/admin/professional-tax-manager'
    | '/admin/service-type-manager'
    | '/admin/customers/branch-manager'
    | '/admin/customers/customer-manager'
    | '/admin/customers/state-manager'
    | '/admin/customers/unit-manager'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/service-type-manager': {
      id: '/admin/service-type-manager'
      path: '/service-type-manager'
      fullPath: '/admin/service-type-manager'
      preLoaderRoute: typeof AdminServiceTypeManagerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/professional-tax-manager': {
      id: '/admin/professional-tax-manager'
      path: '/professional-tax-manager'
      fullPath: '/admin/professional-tax-manager'
      preLoaderRoute: typeof AdminProfessionalTaxManagerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payroll-manager': {
      id: '/admin/payroll-manager'
      path: '/payroll-manager'
      fullPath: '/admin/payroll-manager'
      preLoaderRoute: typeof AdminPayrollManagerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lwf-manager': {
      id: '/admin/lwf-manager'
      path: '/lwf-manager'
      fullPath: '/admin/lwf-manager'
      preLoaderRoute: typeof AdminLwfManagerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/duty-manager': {
      id: '/admin/duty-manager'
      path: '/duty-manager'
      fullPath: '/admin/duty-manager'
      preLoaderRoute: typeof AdminDutyManagerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/control-center': {
      id: '/admin/control-center'
      path: '/control-center'
      fullPath: '/admin/control-center'
      preLoaderRoute: typeof AdminControlCenterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/billing-type-manager': {
      id: '/admin/billing-type-manager'
      path: '/billing-type-manager'
      fullPath: '/admin/billing-type-manager'
      preLoaderRoute: typeof AdminBillingTypeManagerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/allowance-manager': {
      id: '/admin/allowance-manager'
      path: '/allowance-manager'
      fullPath: '/admin/allowance-manager'
      preLoaderRoute: typeof AdminAllowanceManagerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers/unit-manager': {
      id: '/admin/customers/unit-manager'
      path: '/unit-manager'
      fullPath: '/admin/customers/unit-manager'
      preLoaderRoute: typeof AdminCustomersUnitManagerRouteImport
      parentRoute: typeof AdminCustomersRoute
    }
    '/admin/customers/state-manager': {
      id: '/admin/customers/state-manager'
      path: '/state-manager'
      fullPath: '/admin/customers/state-manager'
      preLoaderRoute: typeof AdminCustomersStateManagerRouteImport
      parentRoute: typeof AdminCustomersRoute
    }
    '/admin/customers/customer-manager': {
      id: '/admin/customers/customer-manager'
      path: '/customer-manager'
      fullPath: '/admin/customers/customer-manager'
      preLoaderRoute: typeof AdminCustomersCustomerManagerRouteImport
      parentRoute: typeof AdminCustomersRoute
    }
    '/admin/customers/branch-manager': {
      id: '/admin/customers/branch-manager'
      path: '/branch-manager'
      fullPath: '/admin/customers/branch-manager'
      preLoaderRoute: typeof AdminCustomersBranchManagerRouteImport
      parentRoute: typeof AdminCustomersRoute
    }
  }
}

interface AdminCustomersRouteChildren {
  AdminCustomersBranchManagerRoute: typeof AdminCustomersBranchManagerRoute
  AdminCustomersCustomerManagerRoute: typeof AdminCustomersCustomerManagerRoute
  AdminCustomersStateManagerRoute: typeof AdminCustomersStateManagerRoute
  AdminCustomersUnitManagerRoute: typeof AdminCustomersUnitManagerRoute
}

const AdminCustomersRouteChildren: AdminCustomersRouteChildren = {
  AdminCustomersBranchManagerRoute: AdminCustomersBranchManagerRoute,
  AdminCustomersCustomerManagerRoute: AdminCustomersCustomerManagerRoute,
  AdminCustomersStateManagerRoute: AdminCustomersStateManagerRoute,
  AdminCustomersUnitManagerRoute: AdminCustomersUnitManagerRoute,
}

const AdminCustomersRouteWithChildren = AdminCustomersRoute._addFileChildren(
  AdminCustomersRouteChildren,
)

interface AdminRouteChildren {
  AdminAllowanceManagerRoute: typeof AdminAllowanceManagerRoute
  AdminBillingTypeManagerRoute: typeof AdminBillingTypeManagerRoute
  AdminControlCenterRoute: typeof AdminControlCenterRoute
  AdminCustomersRoute: typeof AdminCustomersRouteWithChildren
  AdminDutyManagerRoute: typeof AdminDutyManagerRoute
  AdminLwfManagerRoute: typeof AdminLwfManagerRoute
  AdminPayrollManagerRoute: typeof AdminPayrollManagerRoute
  AdminProfessionalTaxManagerRoute: typeof AdminProfessionalTaxManagerRoute
  AdminServiceTypeManagerRoute: typeof AdminServiceTypeManagerRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAllowanceManagerRoute: AdminAllowanceManagerRoute,
  AdminBillingTypeManagerRoute: AdminBillingTypeManagerRoute,
  AdminControlCenterRoute: AdminControlCenterRoute,
  AdminCustomersRoute: AdminCustomersRouteWithChildren,
  AdminDutyManagerRoute: AdminDutyManagerRoute,
  AdminLwfManagerRoute: AdminLwfManagerRoute,
  AdminPayrollManagerRoute: AdminPayrollManagerRoute,
  AdminProfessionalTaxManagerRoute: AdminProfessionalTaxManagerRoute,
  AdminServiceTypeManagerRoute: AdminServiceTypeManagerRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
