
UPDATE public.notifications SET link = CASE split_part(title, ' — ', 1)
  WHEN 'Employees' THEN '/admin/employees'
  WHEN 'Client Contracts' THEN '/admin/contracts/client-contracts'
  WHEN 'Contract Resources' THEN '/admin/contracts/client-contracts'
  WHEN 'Customer Manager' THEN '/admin/customers/customer-manager'
  WHEN 'Branch Manager' THEN '/admin/customers/branch-manager'
  WHEN 'Unit Manager' THEN '/admin/customers/unit-manager'
  WHEN 'State Manager' THEN '/admin/customers/state-manager'
  WHEN 'Designation Manager' THEN '/admin/designation-manager'
  WHEN 'Asset Manager' THEN '/admin/asset-manager'
  WHEN 'Duty Manager' THEN '/admin/duty-manager'
  WHEN 'Allowance Manager' THEN '/admin/allowance-manager'
  WHEN 'Billing Type Manager' THEN '/admin/billing-type-manager'
  WHEN 'Cost Component Manager' THEN '/admin/cost-component-manager'
  WHEN 'Company Documents' THEN '/admin/company-documents'
  WHEN 'ESIC Branch Manager' THEN '/admin/esic-branch-manager'
  WHEN 'Ex-Service Manager' THEN '/admin/ex-service-manager'
  WHEN 'Language Manager' THEN '/admin/language-manager'
  WHEN 'LWF Manager' THEN '/admin/lwf-manager'
  WHEN 'Offboarding Reason Manager' THEN '/admin/offboarding-reason-manager'
  WHEN 'Payroll Manager' THEN '/admin/payroll-manager'
  WHEN 'Payroll Days Manager' THEN '/admin/payroll-days-manager'
  WHEN 'Professional Tax Manager' THEN '/admin/professional-tax-manager'
  WHEN 'RBAC' THEN '/admin/rbac'
  WHEN 'Role-Based Access Control' THEN '/admin/rbac'
  WHEN 'Roles Manager' THEN '/admin/roles-manager'
  WHEN 'Service Type Manager' THEN '/admin/service-type-manager'
  WHEN 'Vehicle Inventory' THEN '/admin/vehicles/inventory'
  WHEN 'FastTag Manager' THEN '/admin/vehicles/fastags'
  WHEN 'Vehicle Insurance Manager' THEN '/admin/vehicles/insurances'
  WHEN 'Vehicle PUC Manager' THEN '/admin/vehicles/pucs'
  WHEN 'Service Manager' THEN '/admin/vehicles/service-manager'
  WHEN 'Expense Manager' THEN '/admin/vehicles/expense-manager'
  WHEN 'Attendance' THEN '/admin/attendance'
  WHEN 'Attendance Code Manager' THEN '/admin/attendance-code-manager'
  WHEN 'Payroll' THEN '/admin/payroll'
  WHEN 'Additions' THEN '/admin/additions'
  WHEN 'Addition Type Manager' THEN '/admin/addition-type-manager'
  WHEN 'Deductions' THEN '/admin/deductions'
  WHEN 'Deduction Type Manager' THEN '/admin/deduction-type-manager'
  WHEN 'Inventory Items' THEN '/admin/inventory/items'
  WHEN 'Inventory Warehouses' THEN '/admin/inventory/warehouses'
  WHEN 'Inventory Vendors' THEN '/admin/inventory/vendors'
  WHEN 'Inventory Purchase Orders' THEN '/admin/inventory/purchase-orders'
  WHEN 'Inventory Delivery Challans' THEN '/admin/inventory/goods-receipts'
  WHEN 'Inventory Goods Receipts' THEN '/admin/inventory/goods-receipts'
  WHEN 'Inventory Demands' THEN '/admin/inventory/demands'
  WHEN 'Inventory Issuances' THEN '/admin/inventory/issuances'
  WHEN 'Inventory Transfers' THEN '/admin/inventory/transfers'
  WHEN 'Inventory Collections' THEN '/admin/inventory/collections'
  WHEN 'Inventory Caps' THEN '/admin/inventory/caps'
  WHEN 'Vendor Rate Cards' THEN '/admin/inventory/rate-cards'
  WHEN 'Office Assets' THEN '/admin/office-assets/inventory'
  WHEN 'Office Assets Categories' THEN '/admin/office-assets/categories'
  WHEN 'Office Assets Allocations' THEN '/admin/office-assets/allocations'
  WHEN 'Organization Manager' THEN '/admin/org-settings'
  WHEN 'My Profile' THEN '/admin/profile'
  ELSE link
END
WHERE (link IS NULL OR link = '');
