CREATE TABLE public.designations (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  name text NOT NULL,
  code text NOT NULL DEFAULT '',
  enabled boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.designations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated read designations" ON public.designations FOR SELECT TO authenticated USING (true);
CREATE POLICY "Authenticated write designations" ON public.designations FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Authenticated update designations" ON public.designations FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Authenticated delete designations" ON public.designations FOR DELETE TO authenticated USING (true);

CREATE TRIGGER designations_set_updated_at BEFORE UPDATE ON public.designations
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

INSERT INTO public.designations (name, code) VALUES
('Control Executive','CE'),
('Senior Executive - Sales','SE - S'),
('Senior Executive - HR','SE - HR'),
('Assistant General Manager - Operations','AGMO'),
('Assistant General Manager','AGM'),
('Assistant General Manager - Account & Finance','AGM - A & F'),
('Assistant Vice President','AVP'),
('Senior Vice President','SVP'),
('Field Officer','FO'),
('Fireman','FM'),
('Senior Fireman','SR FM'),
('Facility Warden','FW'),
('Senior HR Executive','SHRE'),
('Operation Manager','OM'),
('Pantry Boy','PB'),
('Security Attendant','SA'),
('Assistant Field Officer','AFO'),
('Assistant Manager (Operations)','AM (Ops)'),
('Driver','DRV'),
('Asst. Operation Manager','AOM'),
('Trust & Safety Officer','TSO'),
('Office Assistant','OA'),
('HR Executive','HR Ext'),
('Executive - Payroll','EP'),
('Surveillance Executive','SE'),
('Store Assistant','SA'),
('HR - Executive','HR - Ext'),
('Payroll & Compliance Manager','PCM'),
('Watchman','Watchman'),
('Manager - Payroll & Compliance','MPC'),
('Legal Officer','LO'),
('Office Boy','OB'),
('MIS EX','MIS Executive'),
('Account Executive','AE'),
('Traffic Officer','Traffic Officer'),
('Lead Control','LC'),
('Store Executive','SE'),
('Deputy General Manager','DGM'),
('Trust & Safety Manager','TSM'),
('SENIOR CONTROL EXECUTIVE','SCE'),
('Operation Executive','OPE'),
('Assistant Manager','ASM'),
('General Manager','GM'),
('Senior Executive HR.','Sr. Executive HR'),
('Executive','Exe'),
('Field Officcer','FO'),
('Field officer','FO -'),
('HR Head','HR Head'),
('Assistant Manager - HR & Payroll','Asst. Mgr HR'),
('Branch Head','BH'),
('Front Desk Executive','FDE'),
('Security Sup.','Security Sup.'),
('Ex. Serviceman Armed Guard','Ex S AM'),
('Field Offiicer','FO'),
('Executive Operations','EO'),
('Assignment Manager','ASM'),
('Admin Executive','Admin Exe'),
('Driver Mukesh Singh','Driver'),
('Manager - Operations','Mgr Ops'),
('Trust and Safety Officer','TSO'),
('Accounts Executive','AE'),
('Manager - Training','Mgr T'),
('Senior Manager - Admin','Sr. Mgr A'),
('Senior Manager Accounts & Finance','Sr. Mgr A & F'),
('Manager - Accounts & Finance','Mgr A & F'),
('Training Officer','TO'),
('Operations Manager','Ops Mgr'),
('Manager Payroll & Complianes','Mgr HR'),
('Receptionist','Receptionist'),
('Executive Sales','ES'),
('Assistant Manager Operations','Assistant Manager (Ops)'),
('Security Officer (ESM)','SOESM'),
('Manager - HR & Payroll','Manager HR'),
('DEO','D.E.O.'),
('Manager - HR & Compliance','Manager HR'),
('Gunman','Gunman'),
('Vigilance Marshalls','Vigilance Marshalls'),
('Security Officer','SOF'),
('Trust and Safety Office','TSO'),
('Operations Consultant','OC'),
('Trust Safety Officer','TSO'),
('Sales Executive','SE'),
('Fire Technician (ERT)','FT'),
('Senoir Fire Technician (ERT)','SFT'),
('Sales Manager','SM'),
('Assistant Manager - Operations & Marketing','AM'),
('Manager Payroll & Compliance','MGR'),
('Manager - Payroll & Compliances','M - P & C'),
('Assistant Manager - Payroll & Compliances','AM - P & C'),
('Trust and Safety Manager','TSM'),
('Control Room Lead','CRL'),
('Asst. Manager Finance & Corporate Affairs','AMFCA'),
('Area Manager','AM'),
('Consultant','Consultant'),
('Security Guard','SG'),
('Control Room Executive','CRE'),
('Asst. Vice President','Asst. VP'),
('Security Manager','SM'),
('HR Intern','HRI'),
('Training Manager','TM'),
('Regional Head','RH'),
('Assistant training Manager','ATM'),
('Transport Supervior','TS'),
('Doorman','DM'),
('Sr Executive Account & Tenders','Sr Exe'),
('Operations Intern','OI'),
('SR. Supervisor','SR. Sup'),
('Hr Executive','HRE'),
('Assistant Training Manager','Asst T M'),
('Legal Manager','Legal Manager'),
('DGM Business Development','DGM'),
('Bouncer 8HR','Bouncer 8HR'),
('Executive Operation','Exe Ops'),
('HR EXE','HR EXE'),
('Lead Command and Control Centre','LCCC'),
('Filed Officer','FO'),
('CCTV Supervisor','CCTV Sup'),
('Executive HR','EXH'),
('Regional Head Telangana','RHT'),
('Executive SCM','ESCM'),
('Assistant Manager HR','AMH'),
('Executive Control','EC'),
('Officer Legal','OL'),
('Office Bony','OB'),
('Vice President','VP'),
('Sr. Executive -HR','SEH'),
('Security Supervisor','SUP 34054'),
('Sr Executive Operations','SEO'),
('Executive Accounts','EA'),
('Receptionist 28989','Rec 28989'),
('Sr. Executive HR & Compliance','SEHC'),
('Patient Guide','PG'),
('Ambulance Driver','AD'),
('General Manager Operations and Training','GMOT'),
('Sr. Field Officer','SFO'),
('Sr Executive Accounts','Sr Exe ACC'),
('Security Intelligence Officer','SIO'),
('Branch Manager','BM'),
('Field  Officer','FO'),
('AGM','AGM'),
('Asst. Manager','Asst MGR'),
('Asst Manager','Asst MGR'),
('Sr. Executive','Sr EXE'),
('Sr Field Officer','Sr FO'),
('Sr Executive','Sr Exe'),
('SG','SG'),
('Operation Mnager','OM'),
('Fire Marshall','Fire M'),
('CIVIL Armed Gurad','CVL'),
('ESM Armed Guard','ESM'),
('Gate Manager','GTM'),
('Asst Manager HR','ASM'),
('HR Manager','HRM'),
('Legal Intern','LI'),
('Ops. & Training Manager','OTM'),
('Associate','AS'),
('Sr. HR Executive','HRE'),
('Sr. Accounts & Billing Executive','SABE'),
('General Manager Operations','GM'),
('Facility Attendant Supervisor','FAS'),
('ASM Greater than One Year','ASM 1 Yr'),
('Retention Allowance','RA'),
('Head Guard','HG29294'),
('BMS Operator','BMS'),
('Manager Operations','Manager Ops'),
('Ex-serviceman Guard','EXG'),
('Manager Accounts & Finance','Manager Accounts & Finance'),
('Executive Accounts & Billing','Executive A&B'),
('Safety Officer','SO'),
('Manager','MGR'),
('Legal Compliance Officer','Legal Compliance Officer'),
('Darban','Darban'),
('DCPO','DCPO'),
('Operations & Business Development Manager','OBDM'),
('SCM Consultant','SCM'),
('Associate Trust & Safety','ATS'),
('Hr & Admin','HR & ADM27266'),
('security guard','SG 22129'),
('Data Entry Operator','DEO'),
('Housekeeping Supervisor','HKS'),
('BMS OPREATOR','BMS'),
('Sr. Executive Operations Support','SE'),
('CCTV Operator','CCTV OPTR.'),
('Security Guard Cum Driver','SGD'),
('Admin Consultant','AC'),
('STENOGRAPHER','STNGPR'),
('Security Guard Bunglow','SGB'),
('Runner','Runner'),
('Peon','Pn'),
('Intern','Intern'),
('CDO','CDO'),
('Ladies Searchers','LS'),
('Office Executive','OE'),
('Sr HR Executive','SHRE 15'),
('Guard Tour System','GTS'),
('Facility Attendant','FA'),
('CC TV Operator','CCTVO'),
('VMS Operator Allowance','VMSO'),
('LDC','LDC'),
('Multitasking Staff','MTS'),
('Service Charges','SC'),
('Civil Security Guard Ware House','CSGWH'),
('Civil Security Guard Omkar Bunglow','CSGOB'),
('Maharashtra Guard Board Leavy','MGBL'),
('Walkie Talkie','WT'),
('Sr. Manager Ops & Marketing','SMOM'),
('Manager Ops & Marketing','MOPM'),
('OT Supervisor','OTS'),
('Civil Security Guard','CSG'),
('Civil Security Supervisor','CSS'),
('Exserviceman Bouncer','EB'),
('Armed Security Escort','ASES'),
('Toll Tax','TT'),
('Vehicle With Driver','VWD'),
('Armed Security Escort Duty with Cash Van','ASE'),
('Sr. Manager Operations & Marketing','SRM'),
('Republic Day Duties','RDD'),
('Director HR & Legal','Dir HL'),
('Cash Van','Cash Van'),
('OT Security Guard','OT Security Guard'),
('OT Housekeeper','OT Housekeeper'),
('Escort Guard','Escort Guard'),
('OT Head Guard','OT'),
('Incentive','Incentive'),
('Petrolling  Duty','Petrolling Duty'),
('Care Taker','CT'),
('Lagal Manager','LM1'),
('Sr. Account Executive','SAE1'),
('Asisit. Account Manager','ASM1'),
('Account Manager','AM1'),
('Admin Manager','ADM'),
('Management Trainee','Management Trainee'),
('Team Leader Cantrol','Team Leader Cantrol'),
('Civil SG','Civil SG'),
('Fire Officer','FO'),
('Gardner','GDR'),
('Electrician','ECT'),
('Computer Operator','Computer Operator'),
('Marshal','MSL'),
('Armed Guard','AG'),
('Traffic Warden','TW'),
('VMS Operator','VMS OPE'),
('Operation Exicutive','OPE'),
('House Keeping','HK'),
('BDE','BDE'),
('Accounts','AC'),
('SENIOR EXECUTIVE','SXE'),
('ASSISTANT MANAGER','AM'),
('DGM','DGM'),
('CFO','CFO'),
('CEO','CEO'),
('Director','DIR'),
('Driver Cum Pump Operator','DCPO'),
('Fire Man','FM'),
('Fire Security Guard','FSG'),
('Ex-Service Men Guard','ESG'),
('Attendant','ATNDT'),
('Bouncer','BNCR'),
('Assist. Security Officer','ASO'),
('Lady Security Guard','LG'),
('Body Guard','BG');